POST https://localhost:8080/
Content-Type: text/json
Accept: text/json
#Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9,es;q=0.8

{
  "name": "valueOne",
  "familyName": "ValueTwo!",
  "properties": {
    "key1": "value1",
    "key2": "value2"
  }
}

###
GET https://localhost:8080/test
Authorization: Basic username=admin,password=admin

###
GET https://localhost:8080/wow

###
GET https://localhost:8080/test/wowzer
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ0ZXN0Iiwic3ViIjoic29tZWJvZHkiLCJhdWQiOlsic29tZWJvZHlfZWxzZSJdLCJleHAiOjE2ODg3NzMwOTUsIm5iZiI6MTY4ODY4NjY5NSwiaWF0IjoxNjg4Njg2Njk1LCJqdGkiOiIxIn0.7iqUlKZ36VX4viYbHlwaWIDZvZ-d03JisAo4BktKDIQ

###
POST https://localhost:8080/login
Content-Type: text/json

{
  "username": "admin",
  "password": "admin"
}