POST https://localhost/
Content-Type: text/json
Accept: text/json
#Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9,es;q=0.8

{
  "name": "valueOne",
  "familyName": "ValueTwo!",
  "properties": {
    "key1": "value1",
    "key2": "value2"
  }
}

###
GET https://localhost/test
Authorization: Basic username=admin,password=admin

###
POST https://localhost/test
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJtZSIsInN1YiI6Im1lIiwiYXVkIjpbInQiLCJ0MiIsInQzIl0sImV4cCI6MTY4ODkxNTYyNSwibmJmIjoxNjg4ODI5MjI1LCJpYXQiOjE2ODg4MjkyMjUsImp0aSI6IjEifQ.987cbkoN6F6ZgxomfBG6WtbVCChRLYd961MIF9XAVwE

{
  "name": "valueOne",
  "familyName": "ValueTwo!",
  "properties": {
    "key1": "value1",
    "key2": "value2"
  }
}

###
GET https://localhost/test/wowzer
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJtZSIsInN1YiI6Im1lIiwiYXVkIjpbInQiLCJ0MSIsInQyIiwidDMiXSwiZXhwIjoxNjg5NTE5MDA1LCJuYmYiOjE2ODk0MzI2MDYsImlhdCI6MTY4OTQzMjYwNiwianRpIjoiMTAwIn0.2Iu--j0sYMSQB6sOoOg-5o8942unre_wWWwpCGvwHaQq-OEm1zy24yMvd4gv7zPheanzRPeqvcPRiqWDnVHfVQ

###
POST https://go-api.localhost/login
Content-Type: text/json

{
  "username" : "admin",
  "password" : "admin"
}